/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttackResult {
  'lootElixir' : bigint,
  'lootGold' : bigint,
  'destructionPercentage' : bigint,
}
export interface Building {
  'constructionEnd' : [] | [Time],
  'level' : bigint,
  'constructionStart' : [] | [Time],
  'buildingType' : BuildingType,
  'location' : Location,
}
export type BuildingType = { 'goldMine' : null } |
  { 'townHall' : null } |
  { 'barracks' : null } |
  { 'wall' : null } |
  { 'elixirStorage' : null } |
  { 'goldStorage' : null } |
  { 'cannon' : null } |
  { 'archerTower' : null } |
  { 'elixirCollector' : null };
export interface Location { 'x' : bigint, 'y' : bigint }
export type Time = bigint;
export type TroopType = { 'barbarian' : null } |
  { 'giant' : null } |
  { 'archer' : null };
export interface _SERVICE {
  'findMatch' : ActorMethod<[], Principal>,
  'getBuildings' : ActorMethod<[], Array<Building>>,
  'getResources' : ActorMethod<[], [bigint, bigint]>,
  'initializePlayer' : ActorMethod<[], undefined>,
  'placeBuilding' : ActorMethod<[Location, BuildingType], undefined>,
  'recordAttack' : ActorMethod<[AttackResult], undefined>,
  'trainTroop' : ActorMethod<[TroopType], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];