/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    x: bigint;
    y: bigint;
}
export interface Building {
    constructionEnd?: Time;
    level: bigint;
    constructionStart?: Time;
    buildingType: BuildingType;
    location: Location;
}
export type Time = bigint;
export interface AttackResult {
    lootElixir: bigint;
    lootGold: bigint;
    destructionPercentage: bigint;
}
export enum BuildingType {
    goldMine = "goldMine",
    townHall = "townHall",
    barracks = "barracks",
    wall = "wall",
    elixirStorage = "elixirStorage",
    goldStorage = "goldStorage",
    cannon = "cannon",
    archerTower = "archerTower",
    elixirCollector = "elixirCollector"
}
export enum TroopType {
    barbarian = "barbarian",
    giant = "giant",
    archer = "archer"
}
export interface backendInterface {
    findMatch(): Promise<Principal>;
    getBuildings(): Promise<Array<Building>>;
    getResources(): Promise<[bigint, bigint]>;
    initializePlayer(): Promise<void>;
    placeBuilding(location: Location, buildingType: BuildingType): Promise<void>;
    recordAttack(result: AttackResult): Promise<void>;
    trainTroop(troopType: TroopType): Promise<void>;
}
import type { Building as _Building, BuildingType as _BuildingType, Location as _Location, Time as _Time, TroopType as _TroopType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async findMatch(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.findMatch();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findMatch();
            return result;
        }
    }
    async getBuildings(): Promise<Array<Building>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildings();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildings();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResources(): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getResources();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResources();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async initializePlayer(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializePlayer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializePlayer();
            return result;
        }
    }
    async placeBuilding(arg0: Location, arg1: BuildingType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBuilding(arg0, to_candid_BuildingType_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBuilding(arg0, to_candid_BuildingType_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async recordAttack(arg0: AttackResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttack(arg0);
            return result;
        }
    }
    async trainTroop(arg0: TroopType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trainTroop(to_candid_TroopType_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trainTroop(to_candid_TroopType_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BuildingType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuildingType): BuildingType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Building_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Building): Building {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    constructionEnd: [] | [_Time];
    level: bigint;
    constructionStart: [] | [_Time];
    buildingType: _BuildingType;
    location: _Location;
}): {
    constructionEnd?: Time;
    level: bigint;
    constructionStart?: Time;
    buildingType: BuildingType;
    location: Location;
} {
    return {
        constructionEnd: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.constructionEnd)),
        level: value.level,
        constructionStart: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.constructionStart)),
        buildingType: from_candid_BuildingType_n5(_uploadFile, _downloadFile, value.buildingType),
        location: value.location
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goldMine: null;
} | {
    townHall: null;
} | {
    barracks: null;
} | {
    wall: null;
} | {
    elixirStorage: null;
} | {
    goldStorage: null;
} | {
    cannon: null;
} | {
    archerTower: null;
} | {
    elixirCollector: null;
}): BuildingType {
    return "goldMine" in value ? BuildingType.goldMine : "townHall" in value ? BuildingType.townHall : "barracks" in value ? BuildingType.barracks : "wall" in value ? BuildingType.wall : "elixirStorage" in value ? BuildingType.elixirStorage : "goldStorage" in value ? BuildingType.goldStorage : "cannon" in value ? BuildingType.cannon : "archerTower" in value ? BuildingType.archerTower : "elixirCollector" in value ? BuildingType.elixirCollector : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Building>): Array<Building> {
    return value.map((x)=>from_candid_Building_n2(_uploadFile, _downloadFile, x));
}
function to_candid_BuildingType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BuildingType): _BuildingType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TroopType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TroopType): _TroopType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TroopType): {
    barbarian: null;
} | {
    giant: null;
} | {
    archer: null;
} {
    return value == TroopType.barbarian ? {
        barbarian: null
    } : value == TroopType.giant ? {
        giant: null
    } : value == TroopType.archer ? {
        archer: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BuildingType): {
    goldMine: null;
} | {
    townHall: null;
} | {
    barracks: null;
} | {
    wall: null;
} | {
    elixirStorage: null;
} | {
    goldStorage: null;
} | {
    cannon: null;
} | {
    archerTower: null;
} | {
    elixirCollector: null;
} {
    return value == BuildingType.goldMine ? {
        goldMine: null
    } : value == BuildingType.townHall ? {
        townHall: null
    } : value == BuildingType.barracks ? {
        barracks: null
    } : value == BuildingType.wall ? {
        wall: null
    } : value == BuildingType.elixirStorage ? {
        elixirStorage: null
    } : value == BuildingType.goldStorage ? {
        goldStorage: null
    } : value == BuildingType.cannon ? {
        cannon: null
    } : value == BuildingType.archerTower ? {
        archerTower: null
    } : value == BuildingType.elixirCollector ? {
        elixirCollector: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
