/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BuildingType = IDL.Variant({
  'goldMine' : IDL.Null,
  'townHall' : IDL.Null,
  'barracks' : IDL.Null,
  'wall' : IDL.Null,
  'elixirStorage' : IDL.Null,
  'goldStorage' : IDL.Null,
  'cannon' : IDL.Null,
  'archerTower' : IDL.Null,
  'elixirCollector' : IDL.Null,
});
export const Location = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
export const Building = IDL.Record({
  'constructionEnd' : IDL.Opt(Time),
  'level' : IDL.Nat,
  'constructionStart' : IDL.Opt(Time),
  'buildingType' : BuildingType,
  'location' : Location,
});
export const AttackResult = IDL.Record({
  'lootElixir' : IDL.Nat,
  'lootGold' : IDL.Nat,
  'destructionPercentage' : IDL.Nat,
});
export const TroopType = IDL.Variant({
  'barbarian' : IDL.Null,
  'giant' : IDL.Null,
  'archer' : IDL.Null,
});

export const idlService = IDL.Service({
  'findMatch' : IDL.Func([], [IDL.Principal], []),
  'getBuildings' : IDL.Func([], [IDL.Vec(Building)], ['query']),
  'getResources' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'initializePlayer' : IDL.Func([], [], []),
  'placeBuilding' : IDL.Func([Location, BuildingType], [], []),
  'recordAttack' : IDL.Func([AttackResult], [], []),
  'trainTroop' : IDL.Func([TroopType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BuildingType = IDL.Variant({
    'goldMine' : IDL.Null,
    'townHall' : IDL.Null,
    'barracks' : IDL.Null,
    'wall' : IDL.Null,
    'elixirStorage' : IDL.Null,
    'goldStorage' : IDL.Null,
    'cannon' : IDL.Null,
    'archerTower' : IDL.Null,
    'elixirCollector' : IDL.Null,
  });
  const Location = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
  const Building = IDL.Record({
    'constructionEnd' : IDL.Opt(Time),
    'level' : IDL.Nat,
    'constructionStart' : IDL.Opt(Time),
    'buildingType' : BuildingType,
    'location' : Location,
  });
  const AttackResult = IDL.Record({
    'lootElixir' : IDL.Nat,
    'lootGold' : IDL.Nat,
    'destructionPercentage' : IDL.Nat,
  });
  const TroopType = IDL.Variant({
    'barbarian' : IDL.Null,
    'giant' : IDL.Null,
    'archer' : IDL.Null,
  });
  
  return IDL.Service({
    'findMatch' : IDL.Func([], [IDL.Principal], []),
    'getBuildings' : IDL.Func([], [IDL.Vec(Building)], ['query']),
    'getResources' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'initializePlayer' : IDL.Func([], [], []),
    'placeBuilding' : IDL.Func([Location, BuildingType], [], []),
    'recordAttack' : IDL.Func([AttackResult], [], []),
    'trainTroop' : IDL.Func([TroopType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };